### ISSUE TITLE
Compilation issues with the newest reshade 5.9

### ISSUE THREAD

**Issue by ppatalong** [ipsusu/IpsuShade#2]
**Describe the bug**
Compilation issues with the newest reshade 5.9 - 

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade / download reshape 5.9 and install into ffxiv
2. Install IpsuShade
3. Run game, reshade should info about compilation issue / if not select present Pastel

**Expected behavior**
No error

**Screenshots**
![obraz](https://github.com/ipsusu/IpsuShade/assets/7189338/00faf869-f0b5-4bdb-a890-0f4e82d1d0e0)

**Desktop (please complete the following information):**
- Windows 10

**Additional context**
Please note that I've managed to fix the issue on my own, just creating issue to learn whether it is actually worth fixing for other players, do Pastel present use that qUINT?
I fixed it by going to https://github.com/martymcmodding/qUINT
and replacing all files with the latest shaders in `\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\reshade-shaders\Shaders`

edit: fixed typo reshape -> reshade

**Comment by ipsusu** [comment]
Thank you for the issue request.  I'm happy to see you've managed to fix it yourself!

I've actually already fixed this in an official way a couple weeks ago, you need to update to IpsuShade v1.0.1 which fixes compatibility with ReShade 5.9+. 

Follow the troubleshooting steps listed here: https://github.com/ipsusu/IpsuShade#troubleshooting-and-common-issues-especially-when-migrating-from-gshade

Or follow the update guide on the release page here: https://github.com/ipsusu/IpsuShade/releases/tag/v1.0.1

(Both have the same steps, essentially.)

**Comment by ipsusu** [comment]
Updating qUINT to the latest version (what you did) technically the best to fix it, but I cannot redistribute an updated version of qUINT due to licencing restrictions. The SSR shader is not great in FFXIV anyway, so I don't use it in any of my presets, so it can be safely deleted.
