### ISSUE TITLE
qUINT_mxao compilation error

### ISSUE THREAD

**Issue by fac42** [ipsusu/IpsuShade#4]
Noticed this issue when I upgraded from the 1.0.1 version of the shaders to 2.0.0 using the latest GPosingWay script/release (8.0.0). Currently have the latest version of ReShade installed (6.1.1). I normally use only the Gameplay or Questing presets but wanted to check out how the higher quality ones looked after updating.

![ffxiv_dx11_07Qje4IbTK](https://github.com/ipsusu/ipsuShade/assets/26045715/63b1cc02-d2f7-4827-b0c7-d1c2f0e46cfb)

EDIT: I did some digging into how GPosingWay works and in the generated ```gposingway-definitions.json``` file I noticed a field titled 'deprecated` with the following values:
```json
"Deprecated": [
    "reshade-shaders\\Shaders\\zfast_crt.fx",
    "reshade-shaders\\Shaders\\crt-royale.fx",
    "reshade-shaders\\Shaders\\FXShaders\\RetroFog.fx",
    "reshade-shaders\\Shaders\\qUINT\\qUINT_mxao.fx",
    "reshade-presets\\Ipsusu"
  ]
```

So I assume that the script is supposed to cleanup/remove these folders and files when it does the install/upgrade, but I noticed that it didn't, as when I first installed it still kept the old 'Ipsusu' presents along with the new 'IpsuShade' ones. The other .fx files listed under 'deprecated' also seem to still exist as well.

Can provide more details if required!

**Comment by ipsusu** [comment]
Hmm... I can't seem to replicate this issue.

I installed ReShade 6.1.1 (with addon support) and installed GPosingway 8.0.0 and seems to load the qUINT_mxao.fx as expected. 

![img](https://i.imgur.com/kvZS7YB.png)

Can you hover the MXAO shader and screenshot the specific compile issue it gives you? Just for future reference.

But, to be honest, probably can be solved by downloading the very latest version of the GPosingway updater / installer and running it again. There were some bug fixes in the past couple of the days and might have solved this issue:
https://github.com/gposingway/gposingway/blob/main/gposingway-update.bat

If it still doesn't fix it, might want to download a fresh copy of the shader from GPosingway: https://github.com/gposingway/gposingway/blob/1e4fd27f55d40b3aae326dd0c107f2b8273d2341/reshade-shaders/Shaders/qUINT_mxao.fx

I know they have a custom version that prevents a specific issue with the shader (GShade version is named "qMXAO", but vanilla ReShade version is named "MXAO", but shares the same filename. So settings applied to either one wont copy across to the different versions automatically...)

**Comment by fac42** [comment]
The hover text I get is as follows:
```Preprocessor Error: could not open included file 'qUINT_common.fxh'```

I'll do another run of the GPosingway script to see if it helps. And if not I'll try downloading the specific shader and copying it over.

EDIT: Ran a diff check between the version of the MXAO shader installed by the script and the version you linked and is identical, so will test again.

EDIT 2: Did the recommended steps in your post above but still seeing the issue unfortunately. Not sure if GPosingWay is cleaning up everything 🤔

**Comment by ipsusu** [comment]
> The hover text I get is as follows: `Preprocessor Error: could not open included file 'qUINT_common.fxh'`
> 
> I'll do another run of the GPosingway script to see if it helps. And if not I'll try downloading the specific shader and copying it over.
> 
> EDIT: Ran a diff check between the version of the MXAO shader installed by the script and the version you linked and is identical, so will test again.
> 
> EDIT 2: Did the recommended steps in your post above but still seeing the issue unfortunately. Not sure if GPosingWay is cleaning up everything 🤔

That's super weird!

Try putting this file into your `reshade-shaders/Shaders` folder:
https://github.com/martymcmodding/qUINT/blob/master/Shaders/qUINT_common.fxh

If not, just maybe delete your `reshade-shaders` and `reshade-presets` folders and try a fresh install of ReShade via the manual update step: [How do I update from ipsuShade v1.0.1 to v2.0.0+?](https://github.com/ipsusu/ipsuShade?tab=readme-ov-file#how-do-i-update-from-ipsushade-v101-to-v200) 

GPosingway *should* be cleaning up the files properly, but I'm not sure as I'm not actually involved with the development of the scripts on the project. @LeonAquitaine, can you advise?

**Comment by fac42** [comment]
> Try putting this file into your reshade-shaders/Shaders folder:
https://github.com/martymcmodding/qUINT/blob/master/Shaders/qUINT_common.fxh

This worked! Thank you :)

I am guessing that my pre-existing install of ReShade 6.1.1 didn't install some of the standard effects/shaders from their installer when I set it up? But not really sure.

**Comment by ipsusu** [comment]
I mean, GPosingway *should* just handle everything for you, so I'm not quite sure what was going on. I'll leave this issue open for now until Leon has had a chance to look at it. But I'm glad that fixed it for you. 

Thanks for reaching out!
