### ISSUE TITLE
7.0, render errors, misplaced shadows

### ISSUE THREAD

**Issue by isvein** [ipsusu/IpsuShade#5]
Hello :)
Nvidia 2070-->556.12 drivers
Latest ipsushade and reshade
Borderless window

I don't know if this is an preset problem or an reshade problem (I think it may be more of an reshade/effects problem), but in cutscenes specially sometimes shadows does not blend in right and floats over for a lack of better wording.

First I thought it was my main monitor but it happens on my 2nd monitor too.

If I turn on FastAO as the note says under Gameplay(FPS and Quality) it gets way worse with shadows misaligning.

**Comment by ipsusu** [comment]
Hey!

You are correct, this is a ReShade error with the Generic Depth addon not properly detecting FFXIV's internal FSR/DLSS resolutions.

You can temporarily fix it by manually selecting the correct depth buffer. I will be one of the ones at the top of this list in the overlay addon settings tab that matches your native resolution (in my case, it was this one):
![ffxiv_dx11_EDAaOHPFkn](https://github.com/ipsusu/ipsuShade/assets/66371247/eece08e3-2265-4c77-a5e3-d34149e78e4e)

I'll have some specific troubleshooting steps at the bottom of my README document soon. Just waiting for the dust to settle so we can be sure what are genuine, persistent issues.

Hope this solves it for ya! Only other way to fix it would be to either disable the ReShade shaders that access the depth buffer or disable Dynamic Resolution (only play at 100% scaling at either native rez or with DLAA).
