### ISSUE TITLE
I broke... something.

### ISSUE THREAD

**Issue by airrichan** [ipsusu/IpsuShade#6]
So. I followed install steps- and everything was going well, until I tried to load a preset. And. Well.
![image](https://github.com/user-attachments/assets/861e66bc-3dfe-464b-9ee9-5e359a8de2ef)
I think something is wrong.
If it helps, these two things are... not compiling and I don't know why. I even tried re-installing Reshade and the shaders.
![image](https://github.com/user-attachments/assets/09a833b6-d0dc-4995-9ab4-e23cab390411)
It's the same error for both.
I am but a simple egg and don't know what I did.

**Comment by ipsusu** [comment]
I have a section on this in the readme: https://github.com/ipsusu/ipsuShade?tab=readme-ov-file#my-game-is-green-or-pink

Your specific issue is caused by duplicate shaders, however
