### ISSUE TITLE
Transparency issue with REST?

### ISSUE THREAD

**Issue by Bleediss** [ipsusu/IpsuShade#7]
Hi, I noticed an issue while using your transparency fix for REST (v1.3.20). It happens whenever I open any UI and flip through it, e.g., my inventory, the crafting log, and the gathering log. Even without shaders, it appears. It's an issue with the default REST config as well, oddly enough (second image).
![ffxiv_dx11_qe8dFCKyw6](https://github.com/user-attachments/assets/246c84df-9ab0-4272-a917-9aa9ead4fcf8)
![ffxiv_dx11_v2ZDUw9yR0](https://github.com/user-attachments/assets/2ad434f9-1cae-42ea-b99d-dd1f8b6733ba)
![ffxiv_dx11_EbgB0mytju](https://github.com/user-attachments/assets/c78a35ac-9d89-4069-857b-edb927359116)

**Comment by ipsusu** [comment]
Yeah I haven't seen this particular issue before, but the REST stuff is definitely a WiP and issues like this are expected. What specific preset were you using here?

**Comment by Bleediss** [comment]
> Yeah I haven't seen this particular issue before, but the REST stuff is definitely a WiP and issues like this are expected. What specific preset were you using here?

I was using a personal edit of your Questing - Vanilla preset when I first noticed it. After the patch, I cannot replicate this issue anymore, so it appears to have resolved itself then, lol.
